---
title: "LS_Biodiversity"
output: html_document
editor_options: 
  chunk_output_type: console
---
#################################################
Title: Biodiversity of % cover as a function of year and people
Purpose: See if time and shorebird people data affect biodiversity of % cover data
Author: LS
Created: 10/28/21

#packages
```{r}
library(readxl)
library(tidyverse)
library(janitor)
library(ggdark)
library(Hmisc)
library(broom)
library(viridis)
library(lubridate)
library(vegan) #for RDA
library(ggpubr)
library(rstatix)
library(broom)
library(purrr)
library(labdsv) #hellinger transformation
```

#load data
```{r}
#shorebird data
shorebird<-read_excel("data/Shorebird_People_Data/Shorebird_People_Data.xlsx")

# transect data (doesn't need alignment - spp consistent throughout)
transect <- read_excel('data/RI_Long_Term_Data/Line_transect_summary_20210413.xlsx')

# target data (needs alignment - spp lists differ by year)
target <- read_excel('data/RI_Long_Term_Data/Photoplot_summary_by_plot_20210414.xlsx')

# alignment info for target data 
align <- read_csv('data/TGT_all.csv')
# see RI_Species_Alighment_Feb21.R for methods
# summary: took species lists for 1990 and 2000, applied to all unique spp.

# timed search
timed_search <- read_excel("data/RI_Long_Term_Data/TimedSearch_plot_counts_20210413.xlsx")

# abiotic data
# sea surface temp from SIO Pier
sst <- read_csv("data/SIO_TEMP.csv", 
                skip = 26)

# tide predictions from tbone tides
tide <- read_csv("data/tbone_tides_hourly_1990_2026.csv", 
                 col_types = cols(datetime = col_datetime(format = "%m/%d/%Y %H:%M")))

# southern oscillation index from NOAA NCEI
soi <- read_excel("data/SOI_Data_NOAA_NCEI_1990_2020.xlsx")
```

#presets
```{r}
# lists of commonly filtered-for items
cabrsites <- c('CAB1', 'CAB2', 'CAB3') 
zonelist <- c('CHT', unique(target$Zone)[1:4])
zonenames <- c('Balanus/Chthamalus', 'Tetraclita rubescens', 'Mussel', 'Silvetia compressa', 'Pollicipes polymerus')
targetlist <- c('CHTBAL', 'TETRUB', 'MUSSEL', 'SILCOM', 'POLPOL')
currentyear <- lubridate::year(Sys.Date())

# facilitate looping over year groups for reporting. make list of years based on current year. 
tenyrs <- c((currentyear - 11):(currentyear - 2))
fiveyrs <- c((currentyear - 6):(currentyear - 1))
allyrs <- c(1990:(currentyear - 1))

# theme arguments
lltheme_heatmap <- theme_bw() + theme(text = element_text(size = 12),
                 # add more space between panels
                 panel.spacing = unit(1, 'lines'),
                 # no background to wrap panels
                 strip.background = element_blank(),
                 strip.text = element_text(size = 12, hjust = 0),
                 # panel labels outside x axis labels
                 strip.placement = 'outside',
                 # adjust x axis labels
                 axis.text.y = element_text(size = 11, color = 'black'),
                 axis.text.x = element_text(size = 11, angle = 45, hjust = 1, color = 'black'),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 legend.position = 'bottom')

lltheme <- theme_bw() + theme(text = element_text(size = 12),
                 # add more space between panels
                 panel.spacing = unit(1, 'lines'),
                 # no background to wrap panels
                 strip.background = element_blank(),
                 strip.text = element_text(size = 12, hjust = 0),
                 # panel labels outside x axis labels
                 strip.placement = 'outside',
                 # adjust x axis labels
                 axis.text.y = element_text(size = 11),
                 axis.text.x = element_text(size = 11, angle = 45, hjust = 1))
```

#tidy shorebird data
```{r}
#add column with just years
shorebird$Year=format(shorebird$SurveyDate, "%Y")

#filter for just people
shorebird2<- ungroup(shorebird) %>% 
  mutate(SurveyYear=year(SurveyDate))%>%
  filter(DataType=="People")%>%
  group_by(SurveyYear, ZoneClass) %>% #separate by year and zone
  summarise(people=mean(DataCount)) %>% #get average counts
  mutate(ZoneName= paste('Zone', ZoneClass),
         Panel = if_else(ZoneName == 'Zone I', 'A', 
                         if_else(ZoneName == 'Zone II', 'B', 'C'))) %>%
  mutate(ZoneName = paste('(', Panel, ') ', ZoneName, sep = '')) %>%
  select(-c(Panel))%>%
  drop_na()
```

#tidy transect data
```{r}
# adapted from B. Hong's 2019-2021 Annual Report Code

# tidy 
transect <- transect %>%
  # remove duplicated rows (not present as of SP20 data)
  distinct() %>%
  # combine PHYOVE (overstory) and PHYUND (understory) to PHYALL
  mutate(
    SpeciesCode = if_else(SpeciesCode %in% c('PHYOVE', 'PHYUND'), 'PHYALL', SpeciesCode),
    Scientific_name = if_else(Scientific_name %in% c('Phyllospadix spp', 'Phyllospadix torreyi (understory)'), 'Seagrass', 
    if_else(Scientific_name == 'Egregia menziesii', 'Boa kelp', Scientific_name))) %>%
  # capitalize first letter of strings
  mutate(Scientific_name = str_to_sentence(Scientific_name)) %>%
  # calculate new totals/% cover with new category
  group_by(SiteCode, SiteName, SurveyYear, Season, SeasonName, SurveyDate, Transect, SpeciesCode, Scientific_name, TotalPoints) %>%
  summarise(points = sum(N)) %>%
  # calculate new % cover
  mutate(pct_cover = (points/TotalPoints)*100)

# further tidy spp names/category specification, etc.
red_turf_spp <- c('ARTCOR', 'OTHRED')

transect2 <-   transect %>%
  filter(SiteCode %in% cabrsites) %>% 
  filter(!is.na(Transect)) %>%
  filter((Transect %in% c(1:2) & SpeciesCode %in% red_turf_spp) |
           (Transect %in% c(3:4) & SpeciesCode == 'PHYALL') |
           (Transect %in% c(5:6) & SpeciesCode == 'EGRMEN')) %>%
  # add transect type column
  mutate(Zone = if_else(Transect %in% 1:2, 'Red algal turf', 
                        if_else(Transect %in% 3:4, 'Phyllospadix', 'Egregia'))) %>%
  # add zone/site column
  mutate(ZoneName = paste('Zone', substr(SiteName, 10, 12)),
         Panel = if_else(SiteName == 'Cabrillo I', 'A', 
                         if_else(SiteName == 'Cabrillo II', 'B', 'C'))) %>%
  mutate(ZoneName = paste('(', Panel, ') ',ZoneName, sep = '')) %>%
  select(-c(Panel))

```

#tidy photoplot data
```{r}
# adapted from B. Hong's 2019-2021 Annual Report Code

# keep target raw, retains plot-level data, and tidy
target <- 
  # add generic codes to this set, along with formatted scientific names
  left_join(target, align, by = 'SpeciesCode') %>%
  # get rid of old scientific name (align has better one)
  select(-c(Scientific_name.x)) %>%
  # rename scientific name column
  rename(Scientific_name = Scientific_name.y) %>%
  # make plot number a numeric column
  mutate(Plot_num = parse_number(substr(Plot_code, 6,6))) %>%
  # add zone/site column
  mutate(ZoneName = paste('Zone', substr(SiteName, 10, 12)),
         Panel = if_else(SiteName == 'Cabrillo I', 'A', 
                         if_else(SiteName == 'Cabrillo II', 'B', 'C'))) %>%
  mutate(ZoneName = paste('(', Panel, ') ', ZoneName, sep='')) %>%
  # only get unique rows (removes duplicates)
  distinct()

unique(target$ZoneName)==unique(shorebird2$ZoneName)

# summarize by 2 methods: all and 1990 (1990-present)

# make list of all possible spp names and codes from target dataset
spplist <- align %>%
  select(SpeciesCode, Scientific_name) %>%
  distinct()

# all categories
target_all <- target %>%
  group_by(SiteCode, SiteName, ZoneName, SurveyYear, Zone, Plot_num, Plot_code, SpeciesCode, Scientific_name) %>%
  summarise(cover = sum(N))


# get total # of pts surveyed per plot in each site/spp/year/season (range = 89-104)
target_summary <- target_all %>%
  group_by(SiteCode, SiteName, ZoneName, SurveyYear, Zone, Plot_num, Plot_code) %>% 
  summarise(points = sum(cover))

# merge w target dataset (to calculate % cover)
target_all <- 
  # align # pts per plot with target 
  left_join(target_all, target_summary) %>%
  # calculate % cover (range of # pts is 89 - 104)
  group_by(SiteCode, SiteName, ZoneName, SurveyYear, Zone, Plot_num, Plot_code, SpeciesCode, Scientific_name) %>%
  mutate(pct_cover = (cover/points)*100) %>%
  # streamline dataset
  select(SiteCode, SiteName, ZoneName, SurveyYear, Zone, Plot_num, Plot_code, SpeciesCode, Scientific_name, pct_cover) 

##########################################################################


# repeat process for 1990
target_1990 <- target %>%
  group_by(SiteCode, SiteName, ZoneName, SurveyYear, Zone, Plot_num, Plot_code, Code_1990) %>%
  summarise(cover = sum(N))

target_1990<- left_join(target_1990, target_summary) %>%
  group_by(SiteCode, ZoneName, SiteName, SurveyYear, Zone, Plot_num, Plot_code, Code_1990) %>%
  mutate(pct_cover = (cover/points)*100) %>%
  select(SiteCode, SiteName, ZoneName, SurveyYear, Zone, Plot_num, Plot_code, Code_1990, pct_cover) %>%
  rename(SpeciesCode = Code_1990) %>%
  filter(SiteName %in% c("Cabrillo I", "Cabrillo II", "Cabrillo III"))

# join spp names to 1990 data
target_1990 <- left_join(target_1990, spplist)

# remove extras
#remove(target_summary, align, spplist, target)

unique(target_1990$ZoneName)

target_90_home <- target_1990 %>%
filter(SiteCode %in% cabrsites) %>%
# filter to only tgt spp in their own plots
filter((Zone == 'CHT' & SpeciesCode %in% c('TETRUB', 'CHTBAL')) |
(Zone == 'MYT' & SpeciesCode == 'MUSSEL') |
(Zone == 'SIL' & SpeciesCode == 'SILCOM') |
(Zone == 'POL' & SpeciesCode == 'POLPOL')) %>%
# get mean + SE cover for each yr
group_by(ZoneName, SurveyYear, Zone, SpeciesCode, Scientific_name) %>%
summarise(Cover_mean = mean(pct_cover), #keep if want each year to have 1 point
Cover_SE = sd(pct_cover)/sqrt(length(pct_cover)))
```

#use target_1990
```{r}
view(target_1990)
#only look at z1 chthamalus plots
# want linear regression with people or year on x. Species richness on y (12 taxonomic groups)


richness<-target_1990%>%
  filter(Zone=="CHT" & ZoneName=="(A) Zone I") %>% #filter by cht and z1
  group_by(SurveyYear, Plot_num)%>%
  filter(pct_cover>0)%>%
  summarise(rich=length(unique(target_1990$SpeciesCode)))

unique(target_1990$SpeciesCode)
#make column that counts unique taxonomic groups per year

```

